language: go

go:
  - "1.14.x"

services:
  - docker

branches:
  only:
    - main
    - master
    - /^release-[0-9]+\..*$/

stages:
  - build
  - release-ff
  - publish

before_script:
  #- git config --global url.git@github.com:open-cluster-management/.insteadOf https://github.com/open-cluster-management/
  - make init

jobs:
  include:

    - stage: build
      name: "build image"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/init
        #- make check
        - make component/build   # to remove overhead and keep output clean
        - make component/push
        #- make security/scans
    
    # - stage: build
    #   name: "build and push coverage image"
    #   script:
    #     - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
    #     - make component/build-coverage
    #     - make component/push-coverage
      
    # - stage: build
    #   name: "build and push e2e image"
    #   if: type = pull_request
    #   script:
    #   - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
    #   - make component/build-e2e
    #   - make component/push-e2e
    
    # - stage: release-ff
    #   name: "Push commits to current release branch"
    #   if: type = push AND branch =~ /^master$/
    #   script:
    #     - make
    #     - make release-ff

    # - stage: publish
    #   name: "Publish Image"
    #   if: type = push AND branch =~ /^release-[0-9]+\..*$/
    #   script:
    #     - make jq/install 
    #     - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
    #   after_script:
    #     - test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_TEST_RESULT" = "1" && ./build/slack-notification.sh || echo "Slack notification not sent"
