apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.leena-ocp.dev02.red-chesterfield.com:6443
  name: api-leena-ocp-dev02-red-chesterfield-com:6443
contexts:
- context:
    cluster: api-leena-ocp-dev02-red-chesterfield-com:6443
    namespace: default
    user: kube:admin/api-leena-ocp-dev02-red-chesterfield-com:6443
  name: default/api-leena-ocp-dev02-red-chesterfield-com:6443/kube:admin
current-context: default/api-leena-ocp-dev02-red-chesterfield-com:6443/kube:admin
kind: Config
preferences: {}
users:
- name: kube:admin/api-leena-ocp-dev02-red-chesterfield-com:6443
  user:
    token: rlTfEqjT9I2D_ylyu8iMv5EhwvfQJfQIFzmAVALUCcw
